### ISSUE TITLE
this repo is missing a feature from the original tool in the itwinjs-core monorepo (working across monorepos)

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/eslint-plugin#28]
It looks like this feature: https://github.com/iTwin/itwinjs-core/pull/5032/files, which merged about 2 days before the initial commit in this repo, never made it into this repo.

This feature was originally used by the transformer which was removed from the core repo which is why it's no longer used, but others recently ran into the same issues that the transformer did which caused this to be implemented. We should patch it back in.

**Comment by aruniverse** [comment]
@yashincontrol,

@eringram is running into an issue due to this missing. can you two work together to restore this?

**Comment by eringram** [comment]
This is still in progress on [this branch](https://github.com/iTwin/eslint-plugin/tree/eringram/no-internal-monorepos). Doing some refactoring to better combine this feature with another feature that allows users to specify package names where `@internal` is not allowed.
