### ISSUE TITLE
Does not work with @bentley/react-scripts@5

### ISSUE THREAD

**Issue by tcobbs-bentley** [iTwin/eslint-plugin#4]
This plugin does not work with @bentley/react-scripts@5. It produces errors in `react-scripts start` and `react-scripts build` saying that the plugin versions don't match between the two packages. I was able to work around the problem by adding the following to my package.json:

```json
  "overrides": {
    "eslint-plugin-react": "7.32.1"
  },
```

I'm guessing that if this package (`@itwin/eslint-plugin`) updates to eslint-plugin-react version 7.32.1, the above workaround will no longer be necessary. Given that this package is designed to work with iTwin stuff, and iTwin stuff is designed to work with @bentley/react-scripts@5, I feel that the two should work together without requiring workarounds like the above.

CC: @aruniverse, @toddsouthenbentley

**Comment by aruniverse** [comment]
We will be updating eslint-plugin to use the latest eslint version
bentley/react-scripts is a fork  of react-scripts with the bare minimum needed to get it working with itwin.js; we do not plan on updating react-scripts to use newer versions of other deps, other than what we needed to add, in order to prevent diverging too much from upstream

**Comment by tcobbs-bentley** [comment]
@aruniverse I don't understand what you are saying. I am not complaining about @bentley/react-scripts. I am saying that this package (@itwin/eslint-plugin) is INCOMPATIBLE with @bentley/react-scripts@5 (without an overrides workaround), and should therefore be updated so that it can be used "out of box". The two MUST work together. Having them be mutually incompatible is unacceptable.

**Comment by yashincontrol** [comment]
@tcobbs-bentley Yes, I am looking into updating the eslint-plugin.
