### ISSUE TITLE
investigate supporting non-flat-config

### ISSUE THREAD

**Issue by MichaelBelousov** [iTwin/eslint-plugin#46]
The latest prereleases drop support for nested (non-flat) config. I was told it was not investigated whether we can keep backwards compatibility. There are several fixes/features that could be used by teams not ready to jump to flat config.

**Comment by MichaelBelousov** [comment]
@Jake-Screen said:

> Me and paulius had looked at some ways that people were trying to set it up that way. but it ended up requiring very weird, convoluted, and obscure npm things to try to get it to work. We ended up deciding to just make the full jump.
>
> We saw an example plugin that was trying it. They had a multi-directory setup that when the linting was called, did a weird npm check on installed versions to then direct the functions to the proper setup. There was no documentation on this at all and was yet to be merged in for this plugin when we were looking at it

**Comment by ben-polinsky** [comment]
Why are they not ready to jump to flat config? These fixes are the carrot :)

**Comment by paulius-valiunas** [comment]
they will have to jump sooner or later, I don't see the point of giving them the illusion they can keep using legacy configs forever. We still have the 3.7 plugin that we have to support according to the iTwin.js support policy, and that one uses a legacy config. I have looked into this possibility before but there is, sadly, no elegant solution to it.

**Comment by MichaelBelousov** [comment]
if you say there is no elegant solution, good enough for me. Closing.
