### ISSUE TITLE
TypeScript 5.3.x incompatibility: TypeError: ts.getResolvedModule is not a function

### ISSUE THREAD

**Issue by ben-polinsky** [iTwin/eslint-plugin#49]
This library is unusable with TypeScript 5.3.x:

`TypeError: ts.getResolvedModule is not a function`

TypeScript has moved the `ts.getResolvedModule` method to an internal API available off the `program` object. 

**To reproduce:**

Upgrade TypeScript to 5.3.x in any project consuming this library, then run eslint.

References: 

https://github.com/microsoft/rushstack/issues/4404#issuecomment-1778015516

https://github.com/microsoft/TypeScript/pull/55818/files#diff-dbfa0e7f632eca196a5ee0e08e00743c46c03799e2704206cfccc065bb6f9e3a

**Comment by anmolshres98** [comment]
Fixed by https://github.com/iTwin/eslint-plugin/pull/51
