### ISSUE TITLE
UiConfig rules don't enforce underscore for private class member variable names.

### ISSUE THREAD

**Issue by bishalatbentley** [iTwin/eslint-plugin#69]

**Comment by ben-polinsky** [comment]
Hi. Can you provide a quick reproduction?

**Comment by bishalatbentley** [comment]
Suppose, we have .tsx files (UI Providers, Tools) where we have classes. And if we use private variables, it doesn't enforce _ for them. Also, the naming convention rule it has for function doesn't seem to work.

```
class MyClass {
  private myVar;
}
```

Ui config doesn't enforce _ for private variable myVar

**Comment by ben-polinsky** [comment]
We've clarified that the uiConfig is not intended for all UI applications.
